export const enum SuperColorStyle {
    BG_BLACK = '40',
    BG_RED = '41',
    BG_GREEN = '42',
    BG_YELLOW = '43',
    BG_BLUE = '44',
    FG_BLACK = '30',
    FG_RED = '31',
    FG_GREEN = '32',
    FG_YELLOW = '33',
    FG_BLUE = '34',
    BOLD = '1',
    ITALIC = '3',
    UNDERLINE = '4',
}
